# tasks file for appsrv
---
- name: Task 1 - Add repo nginx
  become: true
  apt_repository:
    repo: "ppa:nginx/stable"
    state: present
    update_cache: yes

- name: Task 2 - Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Task 3 - Allow all access to tcp port 80
  become: true
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Task 4 - Configure NGINX Proxy  
  become: true
  template:
        src: default.j2
        dest: /etc/nginx/nginx.conf
  notify: 
    - restart nginx
    
- meta: flush_handlers
