# tasks file for appsrv
---
- name: nginx | Add repo
  become: true
  apt_repository:
    repo: "ppa:nginx/stable"
    state: present
    update_cache: yes

- name: Install nginx
  become: true
  apt:
    name: nginx
    state: present

- name: Allow all access to tcp port 80
  become: true
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Configure NGINX LoadBalaccer  
  become: true
  template:
        src: default.j2
        dest: /etc/nginx/nginx.conf
  notify: 
    - restart nginx
    
- meta: flush_handlers
