---
- name: create ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  user: ubuntu
  roles:
    - provision-ec2

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: false
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get update & sudo apt-get -y install python'
  roles:
    - tomcat

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: false
  roles:
    - nginx
