---
- name: apply common configuration to all nodes
  hosts: localhost
  connection: local
  gather_facts: false
  user: ubuntu
  roles:
    - provision-ec2

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: ubuntu
  become: yes
  gather_facts: no
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'
  roles:
    - tomcat
