---
  - name: Task 1 - Install add-apt-repostory
    become: yes
    apt: name=software-properties-common state=latest

  - name: Task 2 - Add Oracle Java Repository
    become: yes
    apt_repository: repo='ppa:webupd8team/java'

  - name: Task 3 - Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Task 4 - Install Oracle Java 8
    apt:
      pkg:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default
      state: present

  - name: Task 5 - Add tomcat group
    group:
      name: tomcat

  - name: Task 6 - Add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no

  - name: Task 7 - Create /opt/tomcat directory
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755

  - name: Task 8 -Download & unarchive Tomcat
    unarchive:
      src: http://apache.cs.utah.edu/tomcat/tomcat-9/v9.0.16/bin/apache-tomcat-9.0.16.tar.gz
      dest: /opt/tomcat
      remote_src: yes
      extra_opts: [--strip-components=1]

  - name: Task 9 - Change ownership Tomcat folder
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory

  - name: Task 10 - Copy Tomcat service file  from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Task 11 - Allow all access to tcp port 8080
    ufw:
      rule: allow
      port: 8080
      proto: tcp

  - name: Task 12 - Reload UFW
    ufw:
      state: reloaded

  - name: Task 12 - Copy sample war to app servers
    become: true
    copy: src=./{{ tomcat_war }} dest=/opt/tomcat/webapps/{{ tomcat_war }} owner=tomcat group=tomcat mode=0744
    
  - name: Task 13 - Start and enable Tomcat service
    systemd:
     name: tomcat
     state: started
     enabled: true

  - name: Task 14 - force systemd to reread configs
    systemd:
      daemon_reload: yes