db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: Q123456w!
    MYSQL_DATABASE: test_db
    MYSQL_USER: test_db_user
    MYSQL_PASSWORD: Q123456w!
#  ports:
#    - "3306:3306"
  volumes:
   - ./db-data/db:/docker-entrypoint-initdb.d

web:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mysql://db:3306/example_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: test_db_user
    JDBC_PASS: Q123456w!
  ports:
   - "80:8080"
  volumes:
   - ./tomcat/webapps:/usr/local/tomcat/webapps
  links:
    - db